name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ExampleProject.Wasm/ExampleProject.Wasm.csproj

      - name: Publish Blazor WASM
        run: dotnet publish ExampleProject.Wasm/ExampleProject.Wasm.csproj -c Release -o ./publish

      - name: Prepare publish dir
        run: |
          mkdir -p publish_root
          cp -r publish/wwwroot/* publish_root/
          ls -la publish_root

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish_root
          publish_branch: gh-pages